import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import ThemeGlobalProvider from "~/context/theme-provider";
import NavBar from "~/components/Navbar";

export const metadata: Metadata = {
  title: "Vino Wallet",
  description: "Generated by create next app",
};

const dnSans = DM_Sans({
  variable: "--font-dm-sans",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${dnSans.variable}`}>
        <ThemeGlobalProvider>
          <NavBar />
          {children}
        </ThemeGlobalProvider>
      </body>
    </html>
  );
}
